#!/usr/bin/env bash
set -uo pipefail

cd "$(cd "$(dirname "$0")" && pwd)"

R='\033[0;31m'; G='\033[0;32m'; C='\033[0;36m'
Y='\033[1;33m'; B='\033[1m'; D='\033[2m'; N='\033[0m'

info()  { echo -e "  ${C}${1}${N}"; }
ok()    { echo -e "  ${G}✓${N} ${1}"; }
warn()  { echo -e "  ${Y}${1}${N}"; }
fail()  { echo -e "  ${R}${1}${N}"; }
header(){ echo -e "\n  ${B}${C}── ${1} ──${N}\n"; }

prompt_yn() {
  local def="$1" msg="$2"
  local disp
  [[ "$def" == "y" ]] && disp="[Y/n]" || disp="[y/N]"
  read -rp "  ${msg} ${disp}: " ans
  [[ -z "$ans" ]] && ans="$def"
  [[ "$ans" =~ ^[YyДд] ]]
}

prompt_val() {
  local msg="$1" def="$2"
  local disp=""
  [[ -n "$def" ]] && disp=" [${def}]"
  read -rp "  ${msg}${disp}: " ans
  echo "${ans:-$def}"
}

prompt_silent() {
  local msg="$1"
  read -srp "  ${msg}: " ans
  echo "$ans"
}

# ─── Go ─────────────────────────────────────────────
check_go() {
  command -v go &>/dev/null || [[ -x /usr/local/go/bin/go ]] || return 1
  return 0
}

install_go() {
  header "Installing Go"

  local arch
  case "$(uname -m)" in
    x86_64)  arch="amd64" ;;
    aarch64) arch="arm64" ;;
    *)       fail "Unsupported architecture: $(uname -m)"; return 1 ;;
  esac

  local go_ver=""
  command -v curl &>/dev/null && go_ver=$(curl -sL https://go.dev/VERSION?m=text 2>/dev/null | head -1)
  command -v wget &>/dev/null && [[ -z "$go_ver" ]] && go_ver=$(wget -qO- https://go.dev/VERSION?m=text 2>/dev/null | head -1)
  [[ -z "$go_ver" ]] && go_ver="go1.24.0"
  go_ver="${go_ver#go}"

  local url="https://go.dev/dl/go${go_ver}.linux-${arch}.tar.gz"
  local tmpf="/tmp/go${go_ver}.tar.gz"

  info "Downloading go${go_ver} (${arch})..."
  if command -v curl &>/dev/null; then
    curl -# -L "$url" -o "$tmpf"
  elif command -v wget &>/dev/null; then
    wget --show-progress -q "$url" -O "$tmpf"
  else
    fail "Neither curl nor wget found. Install one first."
    return 1
  fi

  echo ""
  info "Extracting to /usr/local/go (may ask for sudo)..."
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf "$tmpf" || { fail "Extraction failed"; return 1; }
  rm -f "$tmpf"

  export PATH="/usr/local/go/bin:$PATH"
  if ! grep -q '/usr/local/go/bin' ~/.profile 2>/dev/null; then
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
    info "Added /usr/local/go/bin to ~/.profile"
  fi

  ok "Go ${go_ver} installed"
}

# ─── Config ─────────────────────────────────────────
generate_config() {
  header "Configuration"

  local os_auth="true"
  local token_env="WASH_TOKEN"
  local set_token="false"
  local token_val=""
  local port="9091"
  local allow_0="false"
  local shell="sh"
  local work_dir=""

  prompt_yn "y" "Enable OS authentication?" && os_auth="true" || os_auth="false"
  token_env=$(prompt_val "Token env var name" "$token_env")
  [[ -z "$token_env" ]] && token_env="WASH_TOKEN"
  prompt_yn "n" "Set token value in .env?" && set_token="true" || set_token="false"
  if [[ "$set_token" == "true" ]]; then
    echo ""
    token_val=$(prompt_silent "Token value")
    echo ""
    [[ -z "$token_val" ]] && { fail "Token cannot be empty"; return 1; }
  fi
  port=$(prompt_val "Port" "$port")
  prompt_yn "n" "Listen on 0.0.0.0?" && allow_0="true" || allow_0="false"
  shell=$(prompt_val "Shell command" "$shell")
  work_dir=$(prompt_val "Work directory (empty = home)" "")

  echo ""
  header "Review config.yaml"

  local yaml
  yaml=$(cat <<YAML
# WASH (Web Accessible Shell) configuration file
# Generated by setup-linux.sh

os_auth: ${os_auth}
token: ${token_env}
port: ${port}
allow_0: ${allow_0}
shell: ${shell}
work_dir: ${work_dir}
YAML
)
  echo "$yaml" | sed 's/^/  /'
  echo ""

  cat > config.yaml <<YAML
os_auth: ${os_auth}
token: ${token_env}
port: ${port}
allow_0: ${allow_0}
shell: ${shell}
work_dir: ${work_dir}
YAML
  ok "config.yaml written"

  if [[ "$set_token" == "true" && -n "$token_val" ]]; then
    cat > .env <<ENV
${token_env}=${token_val}
ENV
    chmod 600 .env
    ok ".env written with token"
  fi
}

# ─── Build ──────────────────────────────────────────
build_wash() {
  header "Build"

  if ! check_go; then
    install_go || return 1
  else
    ok "Go $(go version | grep -oP 'go\S+') found"
  fi

  echo ""

  local go_path
  go_path=$(command -v go || echo "/usr/local/go/bin/go")
  info "Running: ${go_path} build -o WASH"
  echo ""

  go build -o WASH . 2>&1 | sed 's/^/  /'
  local rc=${PIPESTATUS[0]}
  if [[ $rc -eq 0 ]]; then
    echo ""
    ok "Build successful! Binary: ${B}WASH${N}"
    ls -lh WASH | sed 's/^/  /'
  else
    echo ""
    fail "Build failed (exit code ${rc})"
    return 1
  fi
}

# ─── Main ──────────────────────────────────────────
clear
echo ""
echo -e "  ${B}══════ WASH — Setup & Build ══════${N}"
echo ""

generate_config || exit 1
build_wash || exit 1

echo ""
ok "All done."
echo ""
