#requires -Version 5.1

$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectDir

$R = "$([char]27)[0;31m"; $G = "$([char]27)[0;32m"
$C = "$([char]27)[0;36m"; $Y = "$([char]27)[1;33m"
$B = "$([char]27)[1m"; $D = "$([char]27)[2m"; $N = "$([char]27)[0m"
$CHECK = "v"

function Info  { Write-Host "  ${C}$args${N}" }
function Ok    { Write-Host "  ${CHECK} ${G}$args${N}" }
function Warn  { Write-Host "  ${Y}$args${N}" }
function Fail  { Write-Host "  ${R}$args${N}" }
function Hdr   { Write-Host "`n  ${B}${C}-- $args --${N}`n" }

function Prompt-YN($def, $msg) {
  $disp = if ($def -eq "y") { "[Y/n]" } else { "[y/N]" }
  $ans = Read-Host "  ${msg} ${disp}"
  if ([string]::IsNullOrEmpty($ans)) { $ans = $def }
  return ($ans -match '^[Yy]')
}

function Prompt-Val($msg, $def) {
  $disp = if ($def) { " [$def]" } else { "" }
  $ans = Read-Host "  ${msg}${disp}"
  if ([string]::IsNullOrEmpty($ans)) { return $def }
  return $ans
}

# в”Ђв”Ђв”Ђ Go в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ
function Check-Go {
  return (Get-Command "go" -ErrorAction SilentlyContinue) -ne $null
}

function Install-Go {
  Hdr "Installing Go"

  $arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }

  $goVer = ""
  try {
    $resp = Invoke-WebRequest -Uri "https://go.dev/VERSION?m=text" -UseBasicParsing -TimeoutSec 10
    $goVer = ($resp.Content -split "`n")[0]
  } catch {}
  if ([string]::IsNullOrEmpty($goVer)) { $goVer = "go1.24.0" }
  $goVer = $goVer -replace "^go", ""

  $msiUrl = "https://go.dev/dl/go${goVer}.windows-${arch}.msi"
  $msiPath = "$env:TEMP\go.msi"

  Info "Downloading go${goVer} for Windows (${arch})..."
  try {
    Start-BitsTransfer -Source $msiUrl -Destination $msiPath
  } catch {
    Warn "BITS unavailable, falling back to Invoke-WebRequest..."
    try {
      Invoke-WebRequest -Uri $msiUrl -OutFile $msiPath -UseBasicParsing
    } catch {
      Fail "Download failed: $_"
      return $false
    }
  }

  Info "Installing Go (may show UAC prompt)..."
  try {
    $proc = Start-Process msiexec.exe -Verb RunAs -Wait -PassThru -ArgumentList "/i `"$msiPath`" /quiet"
    if ($proc.ExitCode -ne 0) {
      Fail "MSI installation failed (exit code $($proc.ExitCode))"
      return $false
    }
  } catch {
    Fail "Installation failed: $_"
    return $false
  }

  $goBin = "${env:ProgramW6432}\Go\bin"
  $userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
  if ($userPath -notlike "*${goBin}*") {
    [Environment]::SetEnvironmentVariable("PATH", "$userPath;$goBin", "User")
  }
  $env:PATH += ";${goBin}"

  if (-not (Test-Path "$goBin\go.exe")) {
    Fail "Go binary not found at ${goBin}. Installation may have failed."
    return $false
  }

  Remove-Item -Force $msiPath -ErrorAction SilentlyContinue
  Ok "Go ${goVer} installed"
  return $true
}

# в”Ђв”Ђв”Ђ Config в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ
function Generate-Config {
  Hdr "Configuration"

  $os_auth = "true"
  $token_env = "WASH_TOKEN"
  $set_token = $false
  $token_val = ""
  $port = "9091"
  $allow_0 = "false"
  $shell = "powershell"
  $work_dir = ""

  if (Prompt-YN "y" "Enable OS authentication?") { $os_auth = "true" } else { $os_auth = "false" }
  $token_env = Prompt-Val "Token env var name" $token_env
  if ([string]::IsNullOrEmpty($token_env)) { $token_env = "WASH_TOKEN" }
  $set_token = Prompt-YN "n" "Set token value in .env?"
  if ($set_token) {
    Write-Host ""
    $token_val = Read-Host -Prompt "  Token value" -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($token_val)
    $token_val = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    Write-Host ""
    if ([string]::IsNullOrEmpty($token_val)) { Fail "Token cannot be empty"; return $false }
  }
  $port = Prompt-Val "Port" $port
  if (Prompt-YN "n" "Listen on 0.0.0.0?") { $allow_0 = "true" } else { $allow_0 = "false" }
  $shell = Prompt-Val "Shell command (powershell, cmd, pwsh)" $shell
  $work_dir = Prompt-Val "Work directory (empty = home)" ""

  Write-Host ""
  Hdr "Review config.yaml"

  $yaml = @"
os_auth: ${os_auth}
token: ${token_env}
port: ${port}
allow_0: ${allow_0}
shell: ${shell}
work_dir: ${work_dir}
"@
  $yaml -split "`n" | ForEach-Object { Write-Host "  $_" }
  Write-Host ""

  @"
# WASH (Web Accessible Shell) configuration file
# Generated by setup-windows.ps1

os_auth: ${os_auth}
token: ${token_env}
port: ${port}
allow_0: ${allow_0}
shell: ${shell}
work_dir: ${work_dir}
"@ | Out-File -FilePath config.yaml -Encoding utf8

  Ok "config.yaml written"

  if ($set_token -and -not [string]::IsNullOrEmpty($token_val)) {
    @"
${token_env}=${token_val}
"@ | Out-File -FilePath .env -Encoding utf8
    Ok ".env written with token"
  }

  return $true
}

# в”Ђв”Ђв”Ђ Build в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ
function Build-Wash {
  Hdr "Build"

  if (-not (Check-Go)) {
    $ok = Install-Go
    if (-not $ok) { return $false }
    if (-not (Check-Go)) {
      Fail "Go still not available after installation. Try restarting your terminal or adding it manually."
      return $false
    }
  } else {
    $goVer = &go version
    $short = $goVer -replace '.*go(\S+).*', '$1'
    Ok "Go $short found"
  }

  Write-Host ""

  $goPath = (Get-Command go).Source
  Info "Running: ${goPath} build -o WASH.exe"
  Write-Host ""

  $output = & go build -o WASH.exe . 2>&1
  $rc = $LASTEXITCODE
  $output | ForEach-Object { Write-Host "  $_" }

  if ($rc -eq 0) {
    Write-Host ""
    Ok "Build successful! Binary: ${B}WASH.exe${N}"
    $item = Get-Item "WASH.exe"
    Write-Host "  $($item.Length / 1KB -as [int]) KB"
  } else {
    Write-Host ""
    Fail "Build failed (exit code ${rc})"
    return $false
  }

  return $true
}

Clear-Host
Write-Host ""
Write-Host "  ${B}====== WASH -- Setup & Build ======${N}"
Write-Host ""

$ok = Generate-Config
if (-not $ok) { exit 1 }

$ok = Build-Wash
if (-not $ok) { exit 1 }

Write-Host ""
Ok "All done."
Write-Host ""
